[package]
name = "proyecto2"
version = "0.1.0"
edition = "2024"

[dependencies]
raylib = "5.5.1"
rand = "0.9.2"
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
rayon = "1.7"

[features]
default = []
raylib_mode = []
